- hosts: all
  become: true

  roles:
    - clone-devstack-gate-to-workspace
    - create-devstack-local-conf
    - install-devstack

- hosts: all
  tasks:
    - name: Dump clouds.yaml
      command: grep -v password /etc/openstack/clouds.yaml

- import_playbook: test.yaml
  vars:
    project_dir: "{{ zuul.project.src_dir }}"
